/* 
 * SensorPush Public API
 *
 * This is a swagger definition for the SensorPush public REST API. Download the definition file [here](https://api.sensorpush.com/api/v1/support/swagger/swagger-v1.json).
 *
 * OpenAPI spec version: v1.0.20200327
 * Contact: support@sensorpush.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Mrc.SensorPushCore.Api;
using Mrc.SensorPushCore.Model;
using Mrc.SensorPushCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Mrc.SensorPushCore.Test
{
    /// <summary>
    ///  Class for testing Gateway
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GatewayTests
    {
        // TODO uncomment below to declare an instance variable for Gateway
        //private Gateway instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Gateway
            //instance = new Gateway();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Gateway
        /// </summary>
        [Test]
        public void GatewayInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Gateway
            //Assert.IsInstanceOfType<Gateway> (instance, "variable 'instance' is a Gateway");
        }


        /// <summary>
        /// Test the property 'LastAlert'
        /// </summary>
        [Test]
        public void LastAlertTest()
        {
            // TODO unit test for the property 'LastAlert'
        }
        /// <summary>
        /// Test the property 'LastSeen'
        /// </summary>
        [Test]
        public void LastSeenTest()
        {
            // TODO unit test for the property 'LastSeen'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Paired'
        /// </summary>
        [Test]
        public void PairedTest()
        {
            // TODO unit test for the property 'Paired'
        }
        /// <summary>
        /// Test the property 'Samples'
        /// </summary>
        [Test]
        public void SamplesTest()
        {
            // TODO unit test for the property 'Samples'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }

    }

}
