/* 
 * SensorPush Public API
 *
 * This is a swagger definition for the SensorPush public REST API. Download the definition file [here](https://api.sensorpush.com/api/v1/support/swagger/swagger-v1.json).
 *
 * OpenAPI spec version: v1.0.20200327
 * Contact: support@sensorpush.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Mrc.SensorPushCore.Api;
using Mrc.SensorPushCore.Model;
using Mrc.SensorPushCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Mrc.SensorPushCore.Test
{
    /// <summary>
    ///  Class for testing Gateways
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GatewaysTests
    {
        // TODO uncomment below to declare an instance variable for Gateways
        //private Gateways instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Gateways
            //instance = new Gateways();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Gateways
        /// </summary>
        [Test]
        public void GatewaysInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Gateways
            //Assert.IsInstanceOfType<Gateways> (instance, "variable 'instance' is a Gateways");
        }



    }

}
