/* 
 * SensorPush Public API
 *
 * This is a swagger definition for the SensorPush public REST API. Download the definition file [here](https://api.sensorpush.com/api/v1/support/swagger/swagger-v1.json).
 *
 * OpenAPI spec version: v1.0.20200327
 * Contact: support@sensorpush.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Mrc.SensorPushCore.Api;
using Mrc.SensorPushCore.Model;
using Mrc.SensorPushCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Mrc.SensorPushCore.Test
{
    /// <summary>
    ///  Class for testing Samples
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SamplesTests
    {
        // TODO uncomment below to declare an instance variable for Samples
        //private Samples instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Samples
            //instance = new Samples();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Samples
        /// </summary>
        [Test]
        public void SamplesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Samples
            //Assert.IsInstanceOfType<Samples> (instance, "variable 'instance' is a Samples");
        }


        /// <summary>
        /// Test the property 'LastTime'
        /// </summary>
        [Test]
        public void LastTimeTest()
        {
            // TODO unit test for the property 'LastTime'
        }
        /// <summary>
        /// Test the property 'Sensors'
        /// </summary>
        [Test]
        public void SensorsTest()
        {
            // TODO unit test for the property 'Sensors'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'TotalSamples'
        /// </summary>
        [Test]
        public void TotalSamplesTest()
        {
            // TODO unit test for the property 'TotalSamples'
        }
        /// <summary>
        /// Test the property 'TotalSensors'
        /// </summary>
        [Test]
        public void TotalSensorsTest()
        {
            // TODO unit test for the property 'TotalSensors'
        }
        /// <summary>
        /// Test the property 'Truncated'
        /// </summary>
        [Test]
        public void TruncatedTest()
        {
            // TODO unit test for the property 'Truncated'
        }

    }

}
