/* 
 * SensorPush Public API
 *
 * This is a swagger definition for the SensorPush public REST API. Download the definition file [here](https://api.sensorpush.com/api/v1/support/swagger/swagger-v1.json).
 *
 * OpenAPI spec version: v1.0.20200327
 * Contact: support@sensorpush.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Mrc.SensorPushCore.Api;
using Mrc.SensorPushCore.Model;
using Mrc.SensorPushCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Mrc.SensorPushCore.Test
{
    /// <summary>
    ///  Class for testing SamplesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SamplesRequestTests
    {
        // TODO uncomment below to declare an instance variable for SamplesRequest
        //private SamplesRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SamplesRequest
            //instance = new SamplesRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SamplesRequest
        /// </summary>
        [Test]
        public void SamplesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SamplesRequest
            //Assert.IsInstanceOfType<SamplesRequest> (instance, "variable 'instance' is a SamplesRequest");
        }


        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'Bulk'
        /// </summary>
        [Test]
        public void BulkTest()
        {
            // TODO unit test for the property 'Bulk'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Test]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Test]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
        /// <summary>
        /// Test the property 'Sensors'
        /// </summary>
        [Test]
        public void SensorsTest()
        {
            // TODO unit test for the property 'Sensors'
        }
        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Test]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }
        /// <summary>
        /// Test the property 'StopTime'
        /// </summary>
        [Test]
        public void StopTimeTest()
        {
            // TODO unit test for the property 'StopTime'
        }

    }

}
