/* 
 * SensorPush Public API
 *
 * This is a swagger definition for the SensorPush public REST API. Download the definition file [here](https://api.sensorpush.com/api/v1/support/swagger/swagger-v1.json).
 *
 * OpenAPI spec version: v1.0.20200327
 * Contact: support@sensorpush.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Mrc.SensorPushCore.Api;
using Mrc.SensorPushCore.Model;
using Mrc.SensorPushCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Mrc.SensorPushCore.Test
{
    /// <summary>
    ///  Class for testing Sensor
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SensorTests
    {
        // TODO uncomment below to declare an instance variable for Sensor
        //private Sensor instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Sensor
            //instance = new Sensor();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Sensor
        /// </summary>
        [Test]
        public void SensorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Sensor
            //Assert.IsInstanceOfType<Sensor> (instance, "variable 'instance' is a Sensor");
        }


        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Alerts'
        /// </summary>
        [Test]
        public void AlertsTest()
        {
            // TODO unit test for the property 'Alerts'
        }
        /// <summary>
        /// Test the property 'BatteryVoltage'
        /// </summary>
        [Test]
        public void BatteryVoltageTest()
        {
            // TODO unit test for the property 'BatteryVoltage'
        }
        /// <summary>
        /// Test the property 'Calibration'
        /// </summary>
        [Test]
        public void CalibrationTest()
        {
            // TODO unit test for the property 'Calibration'
        }
        /// <summary>
        /// Test the property 'DeviceId'
        /// </summary>
        [Test]
        public void DeviceIdTest()
        {
            // TODO unit test for the property 'DeviceId'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
